apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gateway
  name: addressbook-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: addressbook-app
  template:
    metadata:
      name: addressbook-app
      labels:
        app: addressbook-app
    spec:
      containers:
      - name: addressbook-app-container
        image: 999568710647.dkr.ecr.us-west-2.amazonaws.com/addressbook-app:1.12.0
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10

