apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: addressbook-app-ingress
  namespace: gateway
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:999568710647:certificate/e9822346-ba84-4860-b6b0-fdabd5a22827
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]' # HTTPS on port 443
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-port: "8080" # Health check matches the app's service port
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health # Updated health check endpoint
    alb.ingress.kubernetes.io/success-codes: "200" # 200 is standard for health checks
    alb.ingress.kubernetes.io/load-balancer-name: addressbook-app
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=30
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type":"redirect","RedirectConfig":{"Protocol":"HTTPS","Port":"443","StatusCode":"HTTP_301"}}'
spec:
  ingressClassName: alb
  rules:
  - host: address.dominionsystem.org # Specify the hostname
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: addressbook-app-service
            port:
              number: 8080
  tls:
  - hosts:
    - address.dominionsystem.org
    secretName: addressbook-app-tls


